#!/usr/bin/env bash

OPT=$1
UND=`tput smul`
NOUND=`tput rmul`
BLD=`tput bold`
NRML=`tput sgr0`

pdfcompress() {
    # Compress image based PDF size
    gs -sDEVICE=pdfwrite \
       -dCompatibilityLevel=1.4 \
       -dDownsampleColorImages=true \
       -dColorImageResolution=132 \
       -dNOPAUSE -dBATCH \
       -sOutputFile=${1%.pdf}_compressed_$(date +%s).pdf \
       "$1" # The input file to be compressed
}

pdfsplit() {
    gs -sDEVICE=pdfwrite \
       -dNOPAUSE -dBATCH -dSAFER \
       -dFirstPage=${2} \
       -dLastPage=${3} \
       -sOutputFile=${1%.pdf}_p${2}-p${3}.pdf \
       "$1" # The input file to be split
}

cathelp() {
    cat << _EOF
${UND}NAME${NRML}
pdfutils - Simple script to interact with Ghostscript and pdftoppm

${UND}OPTIONS${NRML}
-c|--compress ${UND}pdf-file${NOUND}
    Compress an image based pdf file
-e|--extract ${UND}pdf-file${NOUND}
    Extracts all pages as png files
-s|--split ${UND}pdf-file${NOUND} ${UND}first page of range${NOUND} ${UND}last page of range${NOUND}
    Splits a pdf file based on specified first and last page range into a new pdf file" 
-h|--help
    Prints this help

_EOF
}

# Shifts the arguments by one and makes $2 the $1
shift

case $OPT in
    -c|--compress)
        pdfcompress $1 ;;
    -e|--extract) 
        pdftoppm -png $1 ${1%.pdf} ;;
    -s|--split) 
        pdfsplit $@ ;;
    -h|--help) 
        cathelp ;;
    *)
        echo -e 'Invalid Option\n'
        cathelp
        exit 1 ;;
esac
