#!/usr/bin/env bash

UND=$(tput smul)
NOUND=$(tput rmul)
BLD=$(tput bold)
NRML=$(tput sgr0)

spinner() {
    # Prints a spinning line symbolizing that it's working
    PID=$!
    i=1
    sp="/-\|"
    echo -n ' '
    while [ -d /proc/$PID ]; do
        sleep 0.55
        printf "\b%s" "${sp:i++%${#sp}:1}"
    done
    printf "\bDone\n"
}

pdfcompress() {
    # Compress image based PDF size
    gs -sDEVICE=pdfwrite \
        -dCompatibilityLevel=1.4 \
        -dDownsampleColorImages=true \
        -dColorImageResolution=132 \
        -dNOPAUSE -dBATCH \
        -sOutputFile="${1%.pdf}_compressed_$(date +%s).pdf" \
        "$1" # The input file to be compressed
}

pdfsplit() {
    gs -sDEVICE=pdfwrite \
        -dNOPAUSE -dBATCH -dSAFER \
        -dFirstPage="${2}" \
        -dLastPage="${3}" \
        -sOutputFile="${1%.pdf}_p${2}-p${3}.pdf" \
        "$1" # The input file to be split
}

cathelp() {
    cat <<_EOF
${UND}NAME${NRML}
pdfutils - Simple script to interact with Ghostscript and pdftoppm

${UND}OPTIONS${NRML}
-c|--compress ${UND}pdf-file${NOUND}
    Compress an image based pdf file
-e|--extract ${UND}pdf-file${NOUND}
    Extracts all pages as png files
-s|--split ${UND}pdf-file${NOUND} ${UND}first page of range${NOUND} ${UND}last page of range${NOUND}
    Splits a pdf file based on specified first and last page range into a new pdf file" 
-u|--unite ${UND}pdf-file${NOUND}
    Unites multiple image files into a single pdf file
-h|--help
    Prints this help

_EOF
}

# Shifts the arguments by one and makes $2 the $1
OPT=$1
shift

case $OPT in

-c | --compress)
    pdfcompress "$1" &
    spinner
    ;;
-e | --extract)
    if [[ $1 =~ \.pdf$ ]]; then
        echo 'Extracting png images from the input file'
        pdftoppm -png "$1" "${1%.pdf}" &
        spinner
    fi
    ;;
-s | --split)
    pdfsplit "$@" &
    spinner
    ;;
-u | --unite)
    convert "$@" "$(date +'%a-%F-%H-%M-%S').pdf" &
    spinner
    ;;

-h | --help)
    cathelp
    ;;
*)
    echo -e 'Invalid Option\n'
    cathelp
    exit 1
    ;;

esac
