#!/usr/bin/env bash

Picom() {
    setsid -f picom "$@"
}

PicomRestart() {
    killall -q picom
    sleep 0.1
    Picom "$@"
}

case $1 in

-k) killall picom ;;
-l) setsid -f picom ;;
-v) PicomRestart --vsync ;;
-r) PicomRestart ;;
'') if pgrep -x 'picom' >/dev/null; then killall picom else Picom; fi ;; #Toggle
\?) echo "Error: Invalid option"; exit 1 ;;

esac
