#!/usr/bin/env bash

OffOn() {
    killall picom 
    sleep 0.1
    setsid -f picom $1 --experimental-backends
}

case $1 in
    -o) #Off and On
        OffOn
        exit ;;
    -k) #Kill
        killall picom 
        exit ;;
    -e) #Start with Experimental
        setsid -f picom --experimental-backends 
        exit;;
    -s) #Start with legacy
        setsid -f picom 
        exit ;;
    -n) #Start with no Vsync and Experimental
        OffOn --no-vsync
        exit;;
    \?) # Invalid option
        echo "Error: Invalid option"
        exit;;
esac


if pgrep -x 'picom' > /dev/null ; then
    killall picom
else
    setsid -f picom --experimental-backends
fi
